### ISSUE TITLE
Oak Menu updates

### ISSUE THREAD

**Issue by derekober** [hhgr/OakYork#2]
Adam,

I have a copy of the oak Winter menu and would like to update the website with it. I believe access to that part of the Word Press for oak is missing with Melissa's credentials. Do you mind opening access to that? If so, I can make any and all changes to the menu.  Also, we have the following holiday hours to add if you think it may be easier for you to implement them into the website. Thanks!

Oak.
12/24 – Open @ 4pm
                Dinner – 5-8pm
                Bar Closed @ 8pm
12/25 - Closed

**Comment by AdamChlan** [comment]
Derek, you should be able to edit the menu. If you are on the homepage, and click the “Edit Page” button, you should have all the access you need. Can you give that a try?

As far as the hours, maybe we handle that as an alert. I’ll look at the best way to set this up.

Adam

**Comment by derekober** [comment]
Ah…just noticed the “Page Content Block” Tab…Thank you!

Derek A. Ober
Sales and Marketing Administrator
Heritage Hills
717.755.0123 ext. 1684
717.424.1566

**Comment by AdamChlan** [comment]
When you click the update button to save the content, be patient if it takes a while. Let me know if the page is sluggish for you.

**Comment by derekober** [comment]
It took about 15 seconds to update but should be good now. Thank you, Adam!

Derek A. Ober
Sales and Marketing Administrator
Heritage Hills
717.755.0123 ext. 1684
717.424.1566

**Comment by AdamChlan** [comment]
Derek, I added the hours in the alert bar, so I will close this out.
